### ISSUE TITLE
I missed some required elements

### ISSUE THREAD

**Issue by Sam-Le68** [Sam-Le68/accessibility-fixer-upper#1]
![Screen Shot 2020-04-08 at 4 18 44 AM](https://user-images.githubusercontent.com/55094125/78720539-1848f300-7950-11ea-815d-c702c97153d2.png)

I tried to do the same work as the previous assignment but I do not know my mistakes are.

@muxlowc
@mackenzierose

**Comment by MacKenzieRose** [comment]
Hi Sam,

The first few errors are not because your code is bad, but because of how Markbot is checking your content. Because the marking file is set up to look for all of your navigation to have a class of `nav` it's not seeing your list in your header. The easiest way to fix this is to just add a `class="nav"` to your navigation (although it should be noted that **what you have is correct and functional.**

The second set of errors is because when you use `aria-details` you do not also need any `alt` content. In this instance, leaving your alt tags as `alt=""` is acceptable.

Cheers!
MacKenzie

**Comment by Sam-Le68** [comment]
![Screen Shot 2020-04-09 at 5 37 23 PM](https://user-images.githubusercontent.com/55094125/78886669-d1124d80-7a88-11ea-9afb-e91621dfab6c.png)

Thank you for your help. However, I still have this problem I do not know why.

@muxlowc
@MacKenzieRose

**Comment by muxlowc** [comment]
@Sam-Le68 
I think you just need to add this to your css:

.nav a:hover,
.nav a:focus {
  background-color: #fff;
  color: #113c00;
}

**Comment by Sam-Le68** [comment]
Thank you for your help.
